[Settings]
ID = "Your_Site_ID"

[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/"
  ignore = "git diff --quiet HEAD^ HEAD src/"
  # If skip_processing = true, all other settings are ignored
  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = false
  [build.processing.js]
    bundle = true
    minify = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true
  [build.environment]
    YARN_VERSION = "1.22.0"
    YARN_FLAGS = "--no-ignore-optional"
